routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'SnippetController@index')->name('home');

Auth::routes();

Route::get('auth/associate', 'Auth\AuthController@associate')->name("auth.associate");
Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\AuthController@handleProviderCallback');

Route::get('search', 'SearchController@index')->name('search');

Route::middleware("auth")->group(function() {

    Route::get('/snippets/create', 'UserSnippetController@create')->name('snippets.create');

    Route::resource('snippets', 'UserSnippetController', ['except' =>
      'show', 'create'
    ]);

    Route::post('snippets/{snippet}/comments', 'CommentController@store')->name("comments.store");
    Route::post('comments/{comment}/', 'ReplyController@store')->name("replies.store");

    Route::delete('comments/{comment}', 'CommentController@destroy')->name("comments.destroy");
    Route::delete('replies/{comment}', 'ReplyController@destroy')->name("replies.destroy");

    Route::get("{user}/favourites", "FavouritesController@index")->name("favourites.index");
    Route::get("favourite/{snippet}", "FavouritesController@store")->name("favourites.store");

    Route::delete("/users/{user}/social", "SocialUserController@destroy")->name("user.social.delete");
    Route::get("/users/{user}/social", "SocialUserController@edit")->name("user.social.edit");

    Route::post("/users/{user}/settings", "AccountSettingsController@update")->name("user.updatesettings");
    Route::get("/users/{user}/settings", "AccountSettingsController@edit")->name("user.account.edit");

    Route::get("/users/{user}/edit", "UserProfileController@edit")->name("user.edit");
    Route::post("/users/{user}", "UserProfileController@update")->name("user.update");

    Route::get("notifications", "NotificationsController@index")->name("notifications.index");
    Route::put("notifications", "NotificationsController@update")->name("notifications.update");

});

Route::get('/users/{user}', 'UserProfileController@show')->name("user.show");

Route::get('/snippets/{snippet}', 'UserSnippetController@show')->name('snippets.show');


Route::get('/{user}/{hash}', 'ShareLinkController@show')->name('snippets.private');

Route::view("/privacy-policy", "bullshit.privacypolicy")->name("privacy");
Route::view("/terms-of-service", "bullshit.termsofservice")->name("service");
Route::view("/copyright", "bullshit.copyright");
 

app/Snippet.php
<?php

namespace App;

use Auth;
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Snippet extends Model
{
    use Searchable;
    
    protected $fillable = [
      'name',
      'description',
      'code',
      'language',
      'private'
    ];

    protected $appends = array("favourited");

    public function langaugeCode()
    {
        $languages = config("languages");

        return strtolower($languages[$this->language]);
    }

    public function languageName()
    {
        $languages = config("languages");

        return $languages[$this->language];
    }

    public function user()
    {
        return $this->belongsTo("App\User");
    }

    public function urls()
    {
        return $this->hasOne('App\ShareLink');
    }

    public function tags()
    {
        return $this->hasMany('App\Tag');
    }

    public function isUsers($user_id)
    {
        return $user_id === $this->user_id;
    }

    public function comments()
    {
        return $this->morphMany("App\Comment", "commentable");
    }

    public function favouriter()
    {
        return $this->belongsToMany("App\User", "favourites");
    }

    public function scopeExcludeUsers($query)
    {
        if (Auth::user())
        {
            $query->where("user_id", "!=", Auth::id());
        }
    }

    public function scopePublic($query)
    {
        $query->where("private", false);
    }

    public function scopeMostRecent($query)
    {
        $query->orderBy('updated_at', 'desc');
    }

    public function scopeWithFilters($query)
    {
        $request  = request();
        $language = $request->only("language");
        $sort     = $request->only("sorting");

        if (Auth::user()) {
            switch($request->category) {
                case "MySnippets":
                    $query->where("user_id", Auth::id());
                    break;
                case "favourites":
                    $query->whereHas("favouriter", function ($q) use ($request) {
                        $q->where("favourites.user_id", Auth::id());
                    });
                    break;
            }
        }
            
        foreach($language as $key => $value) {
            if ($value !== "" && $value !== null) {
                $query->where($key, $value);
            }
        }

        foreach($sort as $item) {
            switch($item) {
                case "newest_first":
                    $query->orderBy("created_at", "desc");
                    break;
                case "oldest_first":
                    $query->orderBy("created_at", "asc");
                    break;
                case "recently_updated":
                    $query->orderBy("updated_at", "desc");
                    break;
                case "most_favourited":
                    $query->withCount("favouriter")->orderBy("favouriter_count", "desc");
                    break;
            }
        }

    }

    public function scopeRecommended($query, $snippet)
    {
        $query->where("language", $snippet->language)
              ->where("id", "!=" , $snippet->id)
              ->public()
              ->excludeUsers()
              ->mostRecent();
    }

    public function setTagsAttribute($tags) 
    {   
        foreach ($tags as $tag) {
            if ($tag !== "") {
                $this->tags()->firstOrCreate(["value" => $tag]);
            }
        }
    }

    public function hasTags()
    {
        return $this->tags()->count() > 0;
    }

    public function JsonTags()
    {   
        $array = [];

        foreach($this->tags as $tag) {
            array_push($array, $tag->value);
        }
        
        return collect($array)->ToJson();
    }

    /**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray()
    {   
        $array = $this->toArray();
        
        foreach($this->tags as $index => $tag) {
            $array["tag" . $index] = $tag->value; 
        }
        
        return $array;
    }

    public function getFavouritedAttribute() 
    {
        if (!Auth::user()) {
            return false;
        }

        return Auth::user()->favourites->where("id", $this->id)->count() > 0;
    }

}

app/Http/Controllers/API/SnippetsController.php
<?php

namespace App\Http\Controllers\Api;

use Auth;
use App\Snippet;
use Illuminate\Http\Request;

class SnippetsController extends \App\Http\Controllers\Controller
{

    public function __construct()
    {
        $this->middleware('UsersSnippet')->except("index");
    }

    public function index() 
    {
        $snippets = Snippet::public()
                           ->WithFilters()
                           ->mostRecent()
                           ->with("user")
                           ->paginate(4);

        return response()->json($snippets);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Snippet  $snippet
     * @return \Illuminate\Http\Response
     */
    public function destroy(Snippet $snippet)
    {
        $snippet->delete();

        return response()->json("snippet delete successfully");

    }
}

app/Http/Controllers/SnippetController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\User;
use App\Snippet;
use Illuminate\Http\Request;

class SnippetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $snippets = Snippet::public()
                           ->WithFilters()
                           ->mostRecent()
                           ->with("user")
                           ->paginate(4);

        if (Auth::user())
        {
            $userSnippets = Auth::user()->snippets()->mostRecent()->limit(4)->get();
        }

        $title = "Recently Added";

        return view('snippets.index', compact('snippets', "userSnippets", "title"));
    }

}

resources/views/snippets/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Create a Snippet</h2>
        </div>

        @include("errors")

        <form class="" action="{{ route('snippets.store') }}" method="post">

            @include("snippets.partials.form")

            <div class="col-md-12">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </div>
        </form>

    </div>
</div>

@endsection

@section("deferred")
  <script type="text/javascript">
     Window.EventHandler.$on("code-change", function(code) {
         document.getElementById("code").value = code;
     });
  </script>
@endsection

resources/views/snippets/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Update: {{ $snippet->name }}</h2>
        </div>

        @include("errors")

        <form class="" action="{{ route('snippets.update', $snippet->id) }}" method="post">
            {{ method_field("put") }}

            @include("snippets.partials.form")

            <div class="col-md-12">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </div>
        </form>

    </div>
</div>

@endsection

@section("deferred")
  <script type="text/javascript">
     Window.EventHandler.$on("code-change", function(code) {
         document.getElementById("code").value = code;
     });
  </script>
@endsection

resources/views/snippets/index.blade.php
@extends('layouts.app')

@section('content')

    @guest
        @include("auth.signupbanner")
    @endguest

    <div class="container">
        
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-12">
                    <div class="row" style="display: flex; align-items: flex-start; margin-bottom:22px">
                        <div class="col-sm-6">
                            <h2 style="margin-bottom:0px">{{ $title }}</h2>
                        </div>

                        <div class="col-sm-6 text-right" style="align-self: flex-end; margin-bottom: 0px;">
                            <a href="{{ route("snippets.create") }}" class="btn btn-success">Create a Snippet</a>
                        </div>
                    </div>
                </div>  

                <snippet-list string-snippets="{{ $snippets->toJson() }}" 
                                links='{!! $snippets->links() !!}'
                                user="{{ Auth::user() }}"
                                languages="{{ json_encode(config("languages")) }}">
                </snippet-list>

            </div>
        </div>
    </div> 

@endsection

resources/views/snippets/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container" id="app">
    <div class="row">
        <div class="col-md-8">

            <h2>{{ $snippet->name }} </h2>
            <p>Created by <a href="{{ route("user.show", $snippet->user->username )}}">{{ $snippet->user->username }}</a> about  {{ $snippet->created_at->diffForHumans() }}</p>

            <input type="hidden" value="{{ $snippet->code }}" id="snippet-code">

            <div class="panel panel-default">
                <div class="">
                  <editor read-only="true"
                          code="{{$snippet->code}}"
                          language="{{ $snippet->language }}"
                          options="false"
                          height="450px"
                          ></editor>
                </div>

                 @if(Auth::id() === $snippet->user_id)
                <div class="panel-footer">
                    <a href="{{ route('snippets.edit', $snippet->id) }}" class="btn btn-success pull-left">Update</a>

                    <form action="{{ route('snippets.destroy', $snippet->id) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}

                        <button type="submit" style="margin-left: 5px" class="pull-left btn btn-danger">Delete</button>
                    </form>

                    <div class="" style="clear:both"></div>
                </div>
                @endif

            </div>

            @includeWhen($snippet->isUsers(Auth::id()), "snippets.partials.shareModal")

            <snippet snippet-id="{{ $snippet->id }}" user-id="{{ AUth::id() }}"></snippet>

        </div>

        <div class="col-md-4" style="margin-top: 70px">
            <div class="snippet-description">
                <h3>Description</h3>
                <p>{{ $snippet->description }}</p>
            </div>


            <div class="snippet-options">
                <h3>Options</h3>
                <div class="option-icon-box">
                    <a href="{{ route("favourites.store", $snippet)}}">
                        @if(Auth::user() && Auth::user()->favourites->contains($snippet))
                            <i class="fa fa-star"></i>
                        @else
                            <i class="fa fa-star-o"></i>
                        @endif
                    </a>

                    <button class="no-btn text-primary" data-toggle="modal" data-target="#shareModal">
                        <i class="fa fa-share-square-o" aria-hidden="true"></i>
                    </button>

                    <copy-to-clipboard target-element="code"></copy-to-clipboard>
                </div>
            </div>

            @includeWhen($snippet->hasTags(), "snippets.partials.tags")

        </div>

        @includeWhen(isset($recommended) && $recommended->isNotEmpty(), "snippets.partials.recommended", ["recommended" => $recommended])

    </div>

</div>
@endsection